name: Deploy to Firebase Hosting on merge (dev)
on:
  push:
    branches:
      - dev
jobs:
  build_and_deploy:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: yarn install --frozen-lockfile && npm run build:dev
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_HOSTING_SERVICE_ACCOUNT_DEV }}"
          channelId: live
          projectId: pretty-math-equation
          target: dev
